# Generated by Django 6.0.7 on 2026-07-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام سازمان')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='نام کوتاه')),
                ('organization_type', models.CharField(choices=[('PRIVATE', 'خصوصی'), ('GOVERNMENT', 'دولتی'), ('COOPERATIVE', 'تعاونی'), ('UNIVERSITY', 'دانشگاه'), ('RESEARCH', 'پژوهشی')], default='PRIVATE', max_length=20, verbose_name='نوع سازمان')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('manager', models.CharField(blank=True, max_length=150, verbose_name='مدیر')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
