# Generated by Django 6.0.7 on 2026-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='نام علمی')),
                ('variety', models.CharField(blank=True, max_length=200, verbose_name='رقم')),
                ('season', models.CharField(blank=True, max_length=100, verbose_name='فصل کشت')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
    ]
