# Generated by Django 6.0.7 on 2026-08-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='season',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='variety',
        ),
    ]
