# Generated by Django 6.0.7 on 2026-08-05 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_crop_season_remove_crop_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': 'دسته محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='فصل کشت')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SeedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد شرکت')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('website', models.URLField(blank=True, verbose_name='وب سایت')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شرکت تولیدکننده بذر',
                'verbose_name_plural': 'شرکت\u200cهای تولیدکننده بذر',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='crop',
            name='expected_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عملکرد مورد انتظار (تن در هکتار)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='crops.cropcategory', verbose_name='دسته محصول'),
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد رقم')),
                ('name', models.CharField(max_length=200, verbose_name='نام رقم')),
                ('maturity_days', models.PositiveIntegerField(default=0, verbose_name='دوره رسیدگی (روز)')),
                ('expected_yield', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عملکرد مورد انتظار (تن در هکتار)')),
                ('fruit_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='میانگین وزن میوه (گرم)')),
                ('brix', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='درجه بریکس')),
                ('disease_resistance', models.TextField(blank=True, verbose_name='مقاومت به بیماری')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.crop', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رقم محصول',
                'verbose_name_plural': 'ارقام محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='crops.season', verbose_name='فصل کشت'),
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, unique=True, verbose_name='شماره بچ')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('package_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='وزن بسته (کیلوگرم)')),
                ('germination', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد جوانه زنی')),
                ('purity', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد خلوص')),
                ('moisture', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='رطوبت (%)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت خرید')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='شماره گواهی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeds', to='crops.cropvariety', verbose_name='رقم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeds', to='crops.seedcompany', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'بذر',
                'verbose_name_plural': 'بذرها',
                'ordering': ['-production_date'],
            },
        ),
    ]
