# Generated by Django 6.0.7 on 2026-08-05 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_cropcategory_season_seedcompany_crop_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد بیماری')),
                ('name', models.CharField(max_length=200, verbose_name='نام بیماری')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='نام علمی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('prevention', models.TextField(blank=True, verbose_name='روش پیشگیری')),
                ('treatment', models.TextField(blank=True, verbose_name='روش کنترل')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بیماری',
                'verbose_name_plural': 'بیماری\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('control_method', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'آفت',
                'verbose_name_plural': 'آفات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='crops', to='crops.cropdisease', verbose_name='بیماری\u200cها'),
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ترتیب مرحله')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('start_day', models.PositiveIntegerField(default=0, verbose_name='شروع (روز)')),
                ('end_day', models.PositiveIntegerField(default=0, verbose_name='پایان (روز)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='crops.crop', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مرحله رشد',
                'verbose_name_plural': 'مراحل رشد',
                'ordering': ['crop', 'order'],
                'unique_together': {('crop', 'order')},
            },
        ),
    ]
