# Generated by Django 6.0.7 on 2026-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='طول جغرافیایی')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'موقعیت مکانی',
                'verbose_name_plural': 'موقعیت\u200cهای مکانی',
                'ordering': ['name'],
            },
        ),
    ]
