# Generated by Django 6.0.7 on 2026-07-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
