# Generated by Django 6.0.7 on 2026-08-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_cropdisease_croppest_crop_diseases_cropgrowthstage'),
        ('farmland', '0007_alter_greenhouse_options_alter_reservoir_options_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد درجه')),
                ('name', models.CharField(max_length=100, verbose_name='درجه کیفیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درجه کیفیت',
                'verbose_name_plural': 'درجات کیفیت',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='warehouselocation',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'انبار', 'verbose_name_plural': 'انبارها'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='محل انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, max_length=150, verbose_name='مسئول انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام انبار'),
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد بچ برداشت')),
                ('harvest_date', models.DateField(verbose_name='تاریخ برداشت')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار برداشت')),
                ('unit', models.CharField(default='kg', max_length=30, verbose_name='واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_batches', to='farmland.field', verbose_name='قطعه زمین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_batches', to='crops.crop', verbose_name='محصول')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_batches', to='crops.cropvariety', verbose_name='رقم')),
            ],
            options={
                'verbose_name': 'بچ برداشت',
                'verbose_name_plural': 'بچ\u200cهای برداشت',
                'ordering': ['-harvest_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد موجودی')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='موجودی')),
                ('unit', models.CharField(default='kg', max_length=30, verbose_name='واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='warehouse.harvestbatch', verbose_name='بچ برداشت')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='warehouse.warehouse', verbose_name='انبار')),
                ('quality_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='warehouse.qualitygrade', verbose_name='درجه کیفیت')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبار',
            },
        ),
        migrations.CreateModel(
            name='QualityConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد تبدیل')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('reason', models.TextField(blank=True, verbose_name='علت تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_conversions', to='warehouse.inventorylot', verbose_name='موجودی')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_conversion_from', to='warehouse.qualitygrade', verbose_name='درجه اولیه')),
                ('to_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_conversion_to', to='warehouse.qualitygrade', verbose_name='درجه جدید')),
            ],
            options={
                'verbose_name': 'تبدیل کیفیت',
                'verbose_name_plural': 'تبدیل\u200cهای کیفیت',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد تراکنش')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('TRANSFER', 'انتقال'), ('QUALITY_CHANGE', 'تغییر درجه کیفیت'), ('ADJUSTMENT', 'اصلاح موجودی')], max_length=30, verbose_name='نوع تراکنش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='مقصد')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.inventorylot', verbose_name='موجودی')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
        migrations.DeleteModel(
            name='WarehouseLocation',
        ),
    ]
