# Generated by Django 6.0.7 on 2026-08-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0004_cropdisease_croppest_crop_diseases_cropgrowthstage'),
        ('farmland', '0006_alter_farm_code_alter_farm_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agricultural_year', models.CharField(max_length=20, verbose_name='سال زراعی')),
                ('cultivated_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت زیرکشت')),
                ('planting_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ کاشت')),
                ('planting_density', models.CharField(blank=True, max_length=100, verbose_name='تراکم کاشت')),
                ('planting_method', models.CharField(blank=True, max_length=200, verbose_name='روش کاشت')),
                ('seedling_supplier', models.CharField(blank=True, max_length=200, verbose_name='تأمین\u200cکننده بذر/نشا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_crops', to='crops.crop', verbose_name='محصول')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivations', to='farmland.field', verbose_name='زمین')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_crops', to='crops.cropvariety', verbose_name='رقم')),
            ],
            options={
                'verbose_name': 'کشت زمین',
                'verbose_name_plural': 'کشت\u200cهای زمین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='تاریخ')),
                ('fertilizer', models.CharField(max_length=200, verbose_name='نوع کود')),
                ('amount', models.CharField(max_length=150, verbose_name='مقدار مصرف')),
                ('approved_amount', models.CharField(blank=True, max_length=150, verbose_name='مقدار مصوب')),
                ('application_method', models.CharField(blank=True, max_length=150, verbose_name='روش مصرف')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('field_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='production.fieldcrop', verbose_name='کشت')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=20, verbose_name='شروع برداشت')),
                ('end_date', models.CharField(blank=True, max_length=20, verbose_name='پایان برداشت')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار محصول برداشتی')),
                ('quantity_unit', models.CharField(default='کیلوگرم', max_length=30, verbose_name='واحد')),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='راندمان')),
                ('waste_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ضایعات')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('field_crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='production.fieldcrop', verbose_name='کشت')),
            ],
        ),
        migrations.CreateModel(
            name='PestDiseaseControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='تاریخ')),
                ('problem_type', models.CharField(max_length=150, verbose_name='نوع آفت/بیماری')),
                ('control_method', models.CharField(max_length=200, verbose_name='سم یا روش کنترل')),
                ('amount', models.CharField(blank=True, max_length=150, verbose_name='مقدار مصرف')),
                ('application_method', models.CharField(blank=True, max_length=150, verbose_name='روش اجرا')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('field_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_controls', to='production.fieldcrop', verbose_name='کشت')),
            ],
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ نمونه\u200cگیری')),
                ('parameter', models.CharField(max_length=150, verbose_name='پارامتر')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('ideal_range', models.TextField(blank=True, verbose_name='محدوده ایده\u200cآل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('field_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='production.fieldcrop', verbose_name='کشت')),
            ],
        ),
    ]
