# Generated by Django 6.0.7 on 2026-08-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد دسته')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته کالا',
                'verbose_name_plural': 'دسته\u200cهای کالا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد واحد')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام واحد')),
                ('symbol', models.CharField(blank=True, max_length=20, verbose_name='نماد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'واحد اندازه\u200cگیری',
                'verbose_name_plural': 'واحدهای اندازه\u200cگیری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد انبار')),
                ('name', models.CharField(max_length=200, verbose_name='نام انبار')),
                ('manager', models.CharField(blank=True, max_length=150, verbose_name='مسئول انبار')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='حداقل موجودی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory', verbose_name='دسته کالا')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد تراکنش')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('TRANSFER', 'انتقال')], max_length=10, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='قیمت واحد')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('reference_no', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.product', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.product', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product')],
            },
        ),
    ]
