# Generated by Django 6.0.7 on 2026-08-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد مزرعه')),
                ('name', models.CharField(max_length=200, verbose_name='نام مزرعه')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساحت (هکتار)')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مزرعه',
                'verbose_name_plural': 'مزارع',
                'ordering': ['name'],
            },
        ),
    ]
