# Generated by Django 6.0.7 on 2026-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='farm',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='farm',
            name='manager',
            field=models.CharField(blank=True, max_length=150, verbose_name='مدیر مزرعه'),
        ),
        migrations.AddField(
            model_name='farm',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
