# Generated by Django 6.0.7 on 2026-08-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0002_farm_city_farm_company_farm_description_farm_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد قطعه')),
                ('name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساحت (هکتار)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, verbose_name='نوع خاک')),
                ('irrigation_type', models.CharField(blank=True, max_length=100, verbose_name='نوع آبیاری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farmland.farm', verbose_name='مزرعه')),
            ],
            options={
                'verbose_name': 'قطعه زمین',
                'verbose_name_plural': 'قطعات زمین',
                'ordering': ['name'],
            },
        ),
    ]
