# Generated by Django 6.0.7 on 2026-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0003_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ارتفاع از سطح دریا'),
        ),
        migrations.AlterField(
            model_name='field',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت (هکتار)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد قطعه'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
