# Generated by Django 6.0.7 on 2026-08-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0004_field_elevation_alter_field_area_alter_field_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد گلخانه')),
                ('name', models.CharField(max_length=200, verbose_name='نام گلخانه')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساحت')),
                ('greenhouse_type', models.CharField(blank=True, max_length=100, verbose_name='نوع گلخانه')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to='farmland.field', verbose_name='قطعه زمین')),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoirs', to='farmland.field')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('water_level', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='farmland.field')),
            ],
        ),
    ]
