# Generated by Django 6.0.7 on 2026-08-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0005_greenhouse_reservoir_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد مزرعه'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='field',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد قطعه'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='field',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='field',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد گلخانه'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد مخزن'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='current_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حجم فعلی'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoirs', to='farmland.field', verbose_name='قطعه زمین'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مخزن'),
        ),
        migrations.AlterField(
            model_name='well',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='well',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد چاه'),
        ),
        migrations.AlterField(
            model_name='well',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عمق'),
        ),
        migrations.AlterField(
            model_name='well',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='farmland.field', verbose_name='قطعه زمین'),
        ),
        migrations.AlterField(
            model_name='well',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='well',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام چاه'),
        ),
        migrations.AlterField(
            model_name='well',
            name='water_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سطح آب'),
        ),
    ]
