# Generated by Django 6.0.7 on 2026-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0006_alter_farm_code_alter_farm_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenhouse',
            options={'ordering': ['name'], 'verbose_name': 'گلخانه', 'verbose_name_plural': 'گلخانه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='reservoir',
            options={'ordering': ['name'], 'verbose_name': 'مخزن', 'verbose_name_plural': 'مخازن'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'ordering': ['name'], 'verbose_name': 'چاه', 'verbose_name_plural': 'چاه\u200cها'},
        ),
        migrations.AlterField(
            model_name='field',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساحت (هکتار)'),
        ),
    ]
