# Generated by Django 6.0.7 on 2026-08-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_harvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspector', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='operations.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('special', 'ممتاز'), ('grade1', 'درجه یک'), ('grade2', 'درجه دو'), ('grade3', 'درجه سه'), ('waste', 'ضایعات')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quality.qualityinspection')),
            ],
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passed', models.BooleanField(default=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.qualityinspection')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualitystandard')),
            ],
        ),
    ]
