# Generated by Django 6.0.7 on 2026-07-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Farm Name')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('farm_type', models.CharField(choices=[('traditional', 'Traditional'), ('industrial', 'Industrial'), ('greenhouse', 'Greenhouse'), ('warmhouse', 'Warmhouse')], default='traditional', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Hectare', max_digits=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_farms', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_farms', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('farm', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archive', 'Archive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.block')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('block', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FieldCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.PositiveIntegerField()),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Ton', max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('finished', 'Finished')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.field')),
            ],
            options={
                'ordering': ['-crop_year', 'field'],
            },
        ),
        migrations.CreateModel(
            name='FieldPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinates', models.JSONField(default=list, help_text='Leaflet Polygon Coordinates')),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('zoom', models.PositiveIntegerField(default=17)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polygon', to='farms.field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
