# Generated by Django 6.0.7 on 2026-08-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0004_cropdisease_croppest_crop_diseases_cropgrowthstage'),
        ('farmland', '0005_greenhouse_reservoir_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد عملیات')),
                ('planting_date', models.DateField(verbose_name='تاریخ کاشت')),
                ('expected_harvest_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیش\u200cبینی برداشت')),
                ('cultivated_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سطح زیر کشت (هکتار)')),
                ('seed_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار بذر (کیلوگرم)')),
                ('row_spacing', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='فاصله ردیف (سانتی\u200cمتر)')),
                ('plant_spacing', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='فاصله بوته (سانتی\u200cمتر)')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('planted', 'کشت شده'), ('growing', 'در حال رشد'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], default='planned', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='farmland.field', verbose_name='قطعه زمین')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='crops.seed', verbose_name='بذر')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='crops.cropvariety', verbose_name='رقم')),
            ],
            options={
                'verbose_name': 'عملیات کاشت',
                'verbose_name_plural': 'عملیات کاشت',
                'ordering': ['-planting_date'],
            },
        ),
    ]
