# Generated by Django 6.0.7 on 2026-08-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد برداشت')),
                ('harvest_date', models.DateField(verbose_name='تاریخ برداشت')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='وزن کل (کیلوگرم)')),
                ('grade1_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='درجه یک')),
                ('grade2_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='درجه دو')),
                ('rejected_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خارج از درجه بندی')),
                ('premium_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='درجه ممتاز')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('confirmed', 'تایید شده'), ('closed', 'بسته شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='operations.planting', verbose_name='عملیات کاشت')),
            ],
            options={
                'verbose_name': 'برداشت',
                'verbose_name_plural': 'برداشت\u200cها',
                'ordering': ['-harvest_date'],
            },
        ),
    ]
